"use client";

import { useState } from "react";
import { motion } from "motion/react";
import { Download, Share2, Send } from "lucide-react";

export default function InvoiceDisplaySection({
  pdfUrl,
  feedbackUrl,
  invoiceNumber,
  customerEmail,
  customerName,
  extractedCustomerEmail,
  customerAmount,
  emailSent,
  sendingEmail,
  business,
  onCustomerEmailChange,
  onSendEmail,
  onReset,
}) {
  const [showDropdown, setShowDropdown] = useState(false);

  const handleShare = async () => {
    try {
      const response = await fetch(pdfUrl);
      const blob = await response.blob();
      const file = new File([blob], `Invoice by ${business?.businessName}.pdf`, {
        type: "application/pdf",
      });

      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          title: "Invoice",
          text: "Here's your invoice PDF generated by Invisifeed.",
          files: [file],
        });
      } else {
        alert("Sharing not supported on this device.");
      }
    } catch (error) {
      console.error("Error sharing PDF:", error);
      alert("Failed to share PDF. Please try again.");
    }
  };

  return (
    <div className="max-w-7xl mx-auto mt-8 flex flex-col gap-8">
      {/* Invoice Details */}
      {invoiceNumber && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mt-8 p-5 bg-gradient-to-br from-[#0A0A0A]/80 to-[#0A0A0A]/50 backdrop-blur-sm rounded-xl border border-yellow-400/20 w-full max-w-md mx-auto group relative overflow-hidden"
        >
          <div className="absolute inset-0 bg-gradient-to-br from-yellow-400/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
          <div className="relative">
            <h2 className="text-lg font-bold text-yellow-400">
              Invoice Number
            </h2>
            <p className="text-md font-semibold mb-2 text-white">
              {invoiceNumber}
            </p>
          </div>
          {customerName && (
            <div className="relative">
              <h2 className="text-lg font-bold text-yellow-400">
                Customer Name
              </h2>
              <p className="text-md font-semibold mb-2 text-white">
                {customerName}
              </p>
            </div>
          )}
          {extractedCustomerEmail && (
            <div className="relative">
              <h2 className="text-lg font-bold text-yellow-400">
                Customer Email
              </h2>
              <p className="text-md font-semibold mb-2 text-white">
                {extractedCustomerEmail}
              </p>
            </div>
          )}
          {customerAmount && (
            <div className="relative">
              <h2 className="text-lg font-bold text-yellow-400">
                Total Amount
              </h2>
              <p className="text-md font-semibold mb-2 text-white">
                {customerAmount}
              </p>
            </div>
          )}
        </motion.div>
      )}

      {/* PDF Actions */}
      {pdfUrl && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mt-8 p-5 bg-gradient-to-br from-[#0A0A0A]/80 to-[#0A0A0A]/50 backdrop-blur-sm rounded-xl border border-yellow-400/20 w-full max-w-md mx-auto group relative overflow-hidden"
        >
          <div className="absolute inset-0 bg-gradient-to-br from-yellow-400/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
          <div className="relative flex flex-col gap-4">
            <div className="flex justify-between items-center">
              <h2 className="text-lg font-semibold text-yellow-400">
                Smart Invoice Ready
              </h2>
              <button
                onClick={handleShare}
                className="p-2 hover:bg-yellow-400/10 rounded-full transition-colors"
              >
                <Share2 className="w-5 h-5 text-yellow-400 cursor-pointer" />
              </button>
            </div>

            <div className="w-full max-w-md flex flex-col gap-2">
              {/* Send Email Button */}
              <button
                onClick={() => setShowDropdown(!showDropdown)}
                disabled={sendingEmail || emailSent}
                className="w-full px-6 py-3 bg-gradient-to-r from-white to-gray-200 hover:from-white hover:to-gray-400 text-black font-medium rounded-xl transition-all duration-300 ease-in-out shadow-lg shadow-yellow-500/20 hover:shadow-yellow-500/30 flex items-center justify-center cursor-pointer gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {sendingEmail ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    <span>Sending...</span>
                  </>
                ) : emailSent ? (
                  <>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-5 w-5"
                      viewBox="0 0 20 20"
                      fill="currentColor"
                    >
                      <path
                        fillRule="evenodd"
                        d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                        clipRule="evenodd"
                      />
                    </svg>
                    <span>Email Sent!</span>
                  </>
                ) : (
                  <>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-5 w-5"
                      viewBox="0 0 20 20"
                      fill="currentColor"
                    >
                      <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                      <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                    </svg>
                    <span>Send Email</span>
                  </>
                )}
              </button>

              {/* Email Input Dropdown */}
              <div
                style={{
                  maxHeight: showDropdown ? "500px" : "0px",
                }}
                className="transition-all duration-300 ease-in-out overflow-hidden"
              >
                <div className="mt-3 bg-[#0A0A0A]/50 p-4 rounded-xl border border-yellow-400/10 flex flex-col gap-3">
                  <p className="text-xs text-gray-400 text-center">
                    Email will be sent via <strong>invisifeed@gmail.com</strong>
                  </p>
                  <div className="relative">
                    <input
                      type="email"
                      value={customerEmail}
                      onChange={(e) => onCustomerEmailChange(e.target.value)}
                      placeholder="Enter customer email"
                      className="w-full px-4 py-3 pr-10 bg-[#0A0A0A]/70 border border-yellow-400/20 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:border-yellow-400 focus:ring-1 focus:ring-yellow-400/30 transition-all duration-200"
                      disabled={sendingEmail || emailSent}
                    />
                    <button
                      onClick={onSendEmail}
                      className="absolute inset-y-0 right-3 flex items-center text-yellow-400 hover:text-yellow-300 disabled:opacity-50 cursor-pointer"
                      disabled={!customerEmail || sendingEmail || emailSent}
                    >
                      <Send className="w-5 h-5" />
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Download Button */}
            <a
              href={pdfUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center gap-2 px-6 py-3 bg-gradient-to-r from-yellow-500 to-yellow-400 hover:from-yellow-600 hover:to-yellow-500 text-gray-900 font-medium rounded-xl transition-all duration-300 shadow-lg shadow-yellow-500/20 hover:shadow-yellow-500/30"
            >
              <Download className="h-5 w-5" />
              <span>Download</span>
            </a>
          </div>
        </motion.div>
      )}
    </div>
  );
}
